// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9KBwea36BfnffQ0CqRjS6imtRfvRbWFE',
    appId: '1:537520396433:web:3cbfb0495e0d8d97414730',
    messagingSenderId: '537520396433',
    projectId: 'localizafeira',
    authDomain: 'localizafeira.firebaseapp.com',
    databaseURL: 'https://localizafeira-default-rtdb.firebaseio.com',
    storageBucket: 'localizafeira.appspot.com',
    measurementId: 'G-YPKKLYD1VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuZloc4H9yeqF3y9dWIWdNZqYgyqN13K8',
    appId: '1:537520396433:android:508e80676500f895414730',
    messagingSenderId: '537520396433',
    projectId: 'localizafeira',
    databaseURL: 'https://localizafeira-default-rtdb.firebaseio.com',
    storageBucket: 'localizafeira.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATCerl1KvrrFQRahEOLgQKh5Zy4Vvdc8s',
    appId: '1:537520396433:ios:48ae14c67293c3d5414730',
    messagingSenderId: '537520396433',
    projectId: 'localizafeira',
    databaseURL: 'https://localizafeira-default-rtdb.firebaseio.com',
    storageBucket: 'localizafeira.appspot.com',
    iosBundleId: 'com.example.localizafeira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATCerl1KvrrFQRahEOLgQKh5Zy4Vvdc8s',
    appId: '1:537520396433:ios:f73b3552dfe3e392414730',
    messagingSenderId: '537520396433',
    projectId: 'localizafeira',
    databaseURL: 'https://localizafeira-default-rtdb.firebaseio.com',
    storageBucket: 'localizafeira.appspot.com',
    iosBundleId: 'com.example.localizafeira.RunnerTests',
  );
}
